version: '2'
services:

  dask-worker:
    image: drtools/dask:latest
    command: dask-worker dask-scheduler:8786
    volumes:
      - ./data_root:/usr/share/data/
    depends_on:
      - dask-scheduler

  dask-scheduler:
    image: drtools/dask:latest
    command: dask-scheduler
    volumes:
      - ./data_root:/usr/share/data/
    ports:
      - "8787:8787"

  luigid:
    image: code-challenge/orchestrator:latest
    build:
      context: ./orchestrator
    command: luigid
    ports:
      - "8082:8082"

  orchestrator:
    image: code-challenge/orchestrator:latest
    depends_on:
      - luigid
      - dask-scheduler
    environment:
      - PROJECT_ROOT=$PWD
      - PIPELINE_VERSION=0.1
    volumes:
      - ./data_root:/usr/share/data/ # Mount data directory
      - /var/run/docker.sock:/var/run/docker.sock # Mount docker socker
      - ./orchestrator:/opt/orchestrator # Mount code for faster development
    build:
      context: ./orchestrator
    # TODO: Replace with EvaluateModel task
    command: luigi --module task DownloadData --scheduler-host luigid
